server:
  port: 8100

spring:
  profiles:
    active: ${PROFILE}
  application:
    name: tpdemo
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 5000
      pool-name: datasource-pool-${spring.application.name}
  liquibase:
    change-log: changelog.xml
    url: ${spring.datasource.url}

application:
  fail-percent: 30