apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
        - name: application
          image: zgys/tpdemo:latest
          imagePullPolicy: Always
          env:
            - name: JAVA_ARGS
            - name: JAVA_OPTS
              value: -Xmx128m
          ports:
            - containerPort: 8080
              name: api
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              port: api
              path: /actuator/health
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          readinessProbe:
            failureThreshold: 3
            httpGet:
              port: api
              path: /actuator/health
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          resources:
            limits:
              cpu: 200m
              memory: 384Mi
            requests:
              cpu: 100m
              memory: 128Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: application
  name: application
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: application