apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "postgresql.name" . }}
  labels:
    app: {{ template "postgresql.name" . }}
    chart: {{ template "postgresql.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- if .Values.metrics.customMetrics }}
  custom-metrics.yaml: {{ toYaml .Values.metrics.customMetrics | quote }}
  {{- end }}
  {{- if .Values.pgHbaConf }}
  pg_hba.conf: {{ .Values.pgHbaConf | quote }}
  {{- end }}
